### ISSUE TITLE
Edit and create issue in GamesController

### ISSUE THREAD

**Issue by Nefedov89** [jaric-de/laravel-learn#11]
Use form collection

**Example of edit action**

   /**
     * Edit type.
     *
     * @param \App\Entities\Type $type
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Type $type)
    {
        return view('admin.types.edit', compact('type'));
    }

http://joxi.ru/82QVddLIjkLyNA - edit blade

**Example of create action**
   /**
     * Create type.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.types.create');
    }

http://joxi.ru/DmBXppZhwDEzyA - create blade

**Comment by jaric-de** [comment]
done
