### ISSUE TITLE
Trans

### ISSUE THREAD

**Issue by Nefedov89** [jaric-de/laravel-learn#2]
https://github.com/jaric-de/laravel-learn/blob/0adb11cde3eae30d509d4335c28a7956bf82374e/app/Console/Commands/DeleteInactiveGames.php#L22

Everywhere for text use trans('foo.bar')

**Comment by jaric-de** [comment]
http://joxi.net/V2Vn113fxZE0L2
http://joxi.net/DrlannBuvBb4Rm
