### ISSUE TITLE
Command line ui

### ISSUE THREAD

**Issue by Nefedov89** [jaric-de/laravel-learn#3]
https://github.com/jaric-de/laravel-learn/blob/0adb11cde3eae30d509d4335c28a7956bf82374e/app/Console/Commands/DeleteInactiveGames.php#L41

Add some ui, like  $this->info("Start deleting"); http://joxi.ru/xAeGddBUpO9z1m,  $this->info("Finish deleting");

**Comment by jaric-de** [comment]
done
